---
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data/pg_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - db

  rabbitMq:
    image: rabbitmq:management
    volumes:
      - ./data/rabbit_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitMq

  api:
    build: ./api
    environment:
      - PORT=3000
      - POSTGRES_DB=sports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitMq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=stats_ingest_queue
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - db
      - rabbitMq
    depends_on:
      - db
      - etl
      - rabbitMq

  etl:
    build: ./etl
    environment:
      - POSTGRES_DB=sports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitMq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=stats_ingest_queue
    restart: unless-stopped
    networks:
      - db
      - rabbitMq
    depends_on:
      - db
      - rabbitMq

  dbReaderService:
    build:
      context: ./db-service
      dockerfile: reader.Dockerfile
    environment:
      - POSTGRES_DB=sports
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: unless-stopped
    networks:
      - db
    depends_on:
      - db

networks:
  db:
  rabbitMq:
